### ISSUE TITLE
Unable to get started with syntax theme tutorial on Ubuntu

### ISSUE THREAD

**Issue by BrianBorge** [inkdropapp/inkdrop-default-light-syntax-theme#1]
I'm trying to work through the instructions on how to create a syntax theme without success.  I can't find any discernible errors.  Any advice would be much appreciated.  I've run through the instructions a few times, I hope I'm not missing something obvious - if so I apologize!

### This is what I have tried
- I cloned the repo to `motif-sytax`
- I set Inkdrop to development mode in the settings
- I have reloaded Inkdrop
- I change the theme name in `package.json`
- I ran `ipm link --dev` to symlink the repo
- I reloaded Inkdrop once again

![Screenshot from 2020-01-28 23-00-13](https://user-images.githubusercontent.com/6352760/73326950-01847280-4222-11ea-9cf3-bb6fa3b8d594.png)
![Screenshot from 2020-01-28 23-00-29](https://user-images.githubusercontent.com/6352760/73326951-01847280-4222-11ea-961e-e28daae9fbe8.png)

### Environment Info
Inkdrop Version: 4.5.1

```
➜ ipm -v
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 4.5.1
python 2.7.17
git 2.20.1
```

```
➜ cat package.json
{
  "version": "1.0.0",
  "name": "motif-syntax",
  "description": "Hello world syntax theme",
  "theme": "syntax",
  "styleSheets": ["default.less"],
  "engines": {
    "inkdrop": "^4.x"
  }
}
```

OS: Ubuntu 19.10

Let me know what additional information I can provide.

**Comment by craftzdog** [comment]
Do you have a symlink to your working plugin directory in `~/.config/inkdrop/dev/packages/`?
If you have installed Inkdrop via Snap, the path would be different.
Check the output of `ipm link --dev`.

**Comment by BrianBorge** [comment]
I installed using wget using the instructions here:  https://my.inkdrop.app/download

The sym link is there, this is the output below.

```
➜ ls ~/.config/inkdrop/dev/packages -lah
total 8.0K
drwxr-xr-x 2 myuser myuser 4.0K Jan 29 18:29 .
drwxr-xr-x 3 myuser myuser 4.0K Jan 28 22:34 ..
lrwxrwxrwx 1 myuser myuser   31 Jan 29 18:29 motif-syntax -> /home/myuser/Source/motif-syntax
```

Should I uninstall and use snap instead?  I'll give that a try.

**Comment by craftzdog** [comment]
That's strange. I confirmed that a dev package works on the app installed via deb package on Ubuntu as well.
Please run the below code on Developer Tools Console and tell me the output:

```
inkdrop.config.configDirPath
inkdrop.packages.getAvailablePackagePaths()
```

If `configDirPath` is not `/home/myuser/.config/inkdrop`, it should be a problem.
Also please check if the directory permission is correct.

**Comment by BrianBorge** [comment]
Update - I ended up reinstalling from deb package before seeing your comment and that fixed the the mystery issue I was having.  I'm unsure why though.

![Screenshot from 2020-01-29 21-41-16](https://user-images.githubusercontent.com/6352760/73415552-4078fd80-42e0-11ea-84bc-9a9a29723da2.png)

I super appreciate you taking the time to help me out!

**Comment by craftzdog** [comment]
Congrats! Yeah that's a mystery though 😅 
Looking forward to seeing your syntax theme!
